const SET_FILTERS = 'SET_FILTERS';
const SET_PENDING = 'SET_PENDING';
const SET_FILTER_GROUP_HAS_ADDED_VALUE = 'SET_FILTER_GROUP_HAS_ADDED_VALUE';
const SET_FILTER_GROUP_GET_VALUES_HANDLER = 'SET_FILTER_GROUP_GET_VALUES_HANDLER';

export {
	SET_FILTERS,
	SET_PENDING,
	SET_FILTER_GROUP_HAS_ADDED_VALUE,
	SET_FILTER_GROUP_GET_VALUES_HANDLER
};
