const SET_FILTERS = 'SET_FILTERS';
const SET_FILTER_GROUP_VALUE_HANDLER = 'SET_FILTER_GROUP_VALUE_HANDLER';
const SET_PENDING = 'SET_PENDING';

export {
	SET_FILTERS,
	SET_PENDING,
	SET_FILTER_GROUP_VALUE_HANDLER
};
