const INIT_FIELDS = 'INIT_FIELDS';
const INIT_FORM_NAME = 'INIT_FORM_NAME';
const CHANGE_FILED = 'CHANGE_FILED';
const SET_FORM_VALID = 'SET_FORM_VALID';
const SET_FORM_VALUES = 'SET_FORM_VALUES';
const SET_FORM_VALIDATION_RULES = 'SET_FORM_VALIDATION_RULES';

export {
	INIT_FIELDS,
	INIT_FORM_NAME,
	CHANGE_FILED,
	SET_FORM_VALID,
	SET_FORM_VALUES,
	SET_FORM_VALIDATION_RULES
};
