const SET_PENDING = 'SET_PENDING';
const SET_ACTIVE_CATEGORY_ID = 'SET_ACTIVE_CATEGORY_ID';
const SET_ACTIVE_CATEGORY_NAME = 'SET_ACTIVE_CATEGORY_NAME';
const SET_MEDIA_PRODUCT_CATEGORIES = 'SET_MEDIA_PRODUCT_CATEGORIES';
const SET_HAS_MEDIA_PRODUCT_CATEGORIES = 'SET_HAS_MEDIA_PRODUCT_CATEGORIES';

export {
	SET_PENDING,
	SET_ACTIVE_CATEGORY_ID,
	SET_ACTIVE_CATEGORY_NAME,
	SET_MEDIA_PRODUCT_CATEGORIES,
	SET_HAS_MEDIA_PRODUCT_CATEGORIES
};
