const INIT_FIELDS = 'INIT_FIELDS';
const INIT_FORM_NAME = 'INIT_FORM_NAME';
const CHANGE_FILED_VALUE = 'CHANGE_FILED_VALUE';
const SET_FORM_VALID = 'SET_FORM_VALID';

export {
	INIT_FIELDS,
	INIT_FORM_NAME,
	CHANGE_FILED_VALUE,
	SET_FORM_VALID
};
