export const ADD_FILTER_FORM = 'ADD_FILTER_FORM';
export const EDIT_FILTER_FORM = 'EDIT_FILTER_FORM';

export const ENDPOINT = {
    FILTERS_BASE_CONTROLLER: '/filters',
    GET_ALL_FILTERS: '/filters/all'
};

export const MODALS = {
	DELETE_FILTER_MODAL: 'DELETE_FILTER_MODAL',
	EDIT_FILTER_MODAL: 'EDIT_FILTER_MODAL',
};
