export const ADD_FILTER_FORM = 'ADD_FILTER_FORM';
export const EDIT_FILTER_FORM = 'EDIT_FILTER_FORM';
export const ADD_FILTER_VALUE_FORM = 'ADD_FILTER_VALUE_FORM';

export const ENDPOINT = {
    FILTERS_BASE_CONTROLLER: '/filters',
    FILTER_VALUE_BASE_CONTROLLER: '/filterValues',
    GET_ALL_FILTERS: '/filters/all',
	CREATE_FILTER_GROUP_VALUE: '/filterValues'
};

export const MODALS = {
	DELETE_FILTER_MODAL: 'DELETE_FILTER_MODAL',
	EDIT_FILTER_MODAL: 'EDIT_FILTER_MODAL',
};
