const INIT_FIELDS = 'INIT_FIELDS';
const INIT_FORM_NAME = 'INIT_FORM_NAME';
const SET_FORM_VALID = 'SET_FORM_VALID';
const SET_FIELD_VALUE = 'SET_FIELD_VALUE';
const SET_FORM_VALIDATION_RULES = 'SET_FORM_VALIDATION_RULES';

export {
	INIT_FIELDS,
	INIT_FORM_NAME,
	SET_FORM_VALID,
	SET_FORM_VALIDATION_RULES,
	SET_FIELD_VALUE
};
