import classes from '../styles/index.scss';

export const chevronDown = classes['ti-arrow-down'];
export const chevronUp = classes['ti-arrow-up'];
export const chevronRight = classes['ti-arrow-right'];
export const chevronLeft = classes['ti-arrow-left'];
export const plus = classes['ti-plus'];
export const chartBar = classes['ti-bar-chart'];
export const th = classes['ti-layout-grid3'];
export const filter = classes['ti-filter'];
export const settings = classes['ti-settings'];
export const angleRight = classes['ti-angle-right'];
export const angleUp = classes['ti-angle-up'];
export const angleDown = classes['ti-angle-down'];
export const alignJustify = classes['ti-align-justify'];
export const bell = classes['ti-bell'];
export const cog = classes['ti-settings'];
export const check = classes['ti-check'];
export const exclamation = classes['ti-info'];
export const pencil = classes['ti-pencil'];
export const close = classes['ti-close'];
export const trash = classes['ti-trash'];
